name: Daily Update

on:
  schedule:
    - cron: '0 0 * * *' # Runs daily at midnight (UTC time)

jobs:
  update_profile:
    runs-on: ubuntu-latest

    steps:
      - name: Check out repository
        uses: actions/checkout@v2

      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: '3.x'

      - name: Install dependencies
        run: pip install requests

      - name: Run Python script
        run: python GitActionPerformer.py
        env:
          GITHUB_TOKEN: ${{ secrets.MY_TOKEN }}

      # Additional steps for the "profile readme" workflow can be added here
      - name: Run a one-line script
        run: echo Hello, world!

      - name: Run a multi-line script
        run: |
          echo Add other actions to build,
          echo test, and deploy your project.
